---

- name: Install frontend web services
  yum: pkg={{item}} state=present
  with_items:
   - haproxy

- name: Install haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Enable haproxy
  service: name=haproxy enabled=yes state=started

- name: Allow web traffic through the firewall
  firewalld: service={{ item }} permanent=true state=enabled
  with_items:
   - http
   - https
  notify:
   - restart firewalld
   - wait for firewalld to restart
