---

- name: Install frontend web services
  yum: pkg={{item}} state=present
  with_items:
   - haproxy

- name: Enable haproxy
  service: name=haproxy enabled=yes state=started

- name: Install haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: reload haproxy

- name: Allow web traffic through the firewall
  firewalld: service={{ item }} permanent=true state=enabled
  with_items:
   - http
   - https
  notify:
   - restart firewalld
   - wait for firewalld to restart 

- name: Enable syslog
  lineinfile: >
    dest=/etc/rsyslog.conf
    line='{{ item.value }}'
    state=present
  with_items:
    - { value: '$ModLoad imudp' }
    - { value: '$UDPServerRun 514' }
    - { value: '$UDPServerAddress 127.0.0.1' }
  notify: restart rsyslog
