---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes

  roles:
    - common

#- name: configure and deploy the webservers and application code
#  hosts: webservers
#  remote_user: root
#
#  roles:
#    - web
