---

- name: Install rabbitmq-server services
  yum: pkg={{item}} state=present
  with_items:
   - rabbitmq-server

- name: Enable rabbitmq-server
  service: name=rabbitmq-server enabled=yes state=started

- name: Enable rabbitmq plugins
  rabbitmq_plugin: names={{ item }} state=enabled
  with_items:
   - rabbitmq_management
  notify:
   - restart rabbitmq

- name: Allow rabbit traffic through the firewall
  firewalld: zone=public port={{ item }}/tcp permanent=true state=enabled
  with_items:
   - 5672
   - 15672
  notify:
   - restart firewalld
   - wait for firewalld to restart

- name: Set rabbitmq settings
  lineinfile: >
    dest=/etc/systemd/system/rabbitmq-server.service.d/open_files.conf
    regexp='{{ item.regex }}'
    line='{{ item.value }}'
    state=present
    create=yes
    owner=root
    group=root
  with_items:
    - { regex: '^[Service]', value: '[Service]' }
    - { regex: '^LimitNOFILE=', value: 'LimitNOFILE=102400' }
  notify:
   - restart rabbitmq
   - reload systemctl
